
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import os
import shutil

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, filedialog


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"./assets/frame0")

def open_file_dialog(entry):
    entry.delete(0, 'end')
    folder_selected = filedialog.askdirectory()
    entry.insert(0, folder_selected)

def copy_files():
    print("Copiado de archivos...")

    file_names = []
    print("Leyendo pedimentos...")
    with open("archivos.txt", "r") as file:
        for line in file:
            file_names.append(line.strip())
    print("Cantidad de archivos a buscar: ", len(file_names))

    # Búsqueda de archivos en la carpeta especificada y guardado en la carpeta especificada
    origin_path = entry_1.get()
    save_path = entry_2.get()
    file_terminals = entry_3.get().split(',')

    all_files = os.listdir(origin_path)

    for file_name in file_names:
        for terminal in file_terminals:
            matching_files = list(filter(lambda x: file_name in x and terminal in x, all_files))
            if len(matching_files) > 0:
                for file in matching_files:
                    shutil.copy(os.path.join(origin_path, file), save_path)
    print("Archivos copiados")
    print("Proceso terminado")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("700x470")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 470,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    700.0,
    50.0,
    fill="#DAD9D9",
    outline="")

canvas.create_text(
    15.0,
    3.0,
    anchor="nw",
    text="Copy & Paste",
    fill="#474747",
    font=("Khula SemiBold", 32 * -1)
)

canvas.create_text(
    17.0,
    67.0,
    anchor="nw",
    text="Carpeta de origen",
    fill="#000000",
    font=("Khula SemiBold", 20 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    316.0,
    127.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=32.0,
    y=102.0,
    width=568.0,
    height=48.0
)

canvas.create_text(
    17.0,
    155.0,
    anchor="nw",
    text="Carpeta de destino",
    fill="#000000",
    font=("Khula SemiBold", 20 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    316.0,
    215.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=32.0,
    y=190.0,
    width=568.0,
    height=48.0
)

canvas.create_text(
    16.0,
    243.0,
    anchor="nw",
    text="Terminaciones de archivos (Comas sin espacio: “PD.pdf,PS.pdf”)",
    fill="#000000",
    font=("Khula SemiBold", 20 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    350.0,
    303.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=31.0,
    y=278.0,
    width=638.0,
    height=48.0
)

canvas.create_text(
    16.0,
    331.0,
    anchor="nw",
    text="Pedimentos",
    fill="#000000",
    font=("Khula SemiBold", 20 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: os.startfile(os.path.join(os.path.dirname(os.path.realpath(__file__)), 'archivos.txt')),
    relief="flat"
)
button_1.place(
    x=15.0,
    y=366.0,
    width=330.0,
    height=50.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: copy_files(),
    relief="flat"
)
button_2.place(
    x=356.0,
    y=366.0,
    width=330.0,
    height=50.0
)

canvas.create_rectangle(
    0.0,
    440.0,
    700.0,
    470.0,
    fill="#3B3B3B",
    outline="")

canvas.create_text(
    6.0,
    443.0,
    anchor="nw",
    text="@karen_Fernandez",
    fill="#FFFFFF",
    font=("Khula SemiBold", 15 * -1)
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_file_dialog(entry_1),
    relief="flat"
)
button_3.place(
    x=635.0,
    y=102.0,
    width=50.0,
    height=50.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_file_dialog(entry_2),
    relief="flat"
)
button_4.place(
    x=635.0,
    y=190.0,
    width=50.0,
    height=50.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    670.0,
    25.0,
    image=image_image_1
)
window.resizable(False, False)
window.mainloop()
